#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

fail() { echo "FAIL $*" >&2; exit 1; }
pass() { echo "PASS $*"; }

need_file() {
  local p="$1"
  [ -f "$p" ] || fail "missing file: $p"
}

read_env_key() {
  local file="$1"
  local key="$2"
  python3 - "$file" "$key" <<'PY'
from __future__ import annotations
from pathlib import Path
import sys

path = Path(sys.argv[1])
k = sys.argv[2]
for raw in path.read_text().splitlines():
    line = raw.strip()
    if not line or line.startswith("#") or "=" not in line:
        continue
    kk, vv = line.split("=", 1)
    if kk.strip() != k:
        continue
    v = vv.strip().strip('"').strip("'")
    if v:
        print(v)
        raise SystemExit(0)
raise SystemExit(1)
PY
}

need_file "backend/.env" "create backend/.env first"
need_file "frontend/.env.local" "create frontend/.env.local first"

SUPABASE_URL="$(read_env_key backend/.env SUPABASE_URL || true)"
SERVICE_ROLE_KEY="$(read_env_key backend/.env SUPABASE_SERVICE_ROLE_KEY || true)"
SUPABASE_SECRET_KEY="$(read_env_key backend/.env SUPABASE_SECRET_KEY || true)"
SUPABASE_SECRET="$(read_env_key backend/.env SUPABASE_SECRET || true)"
SUPABASE_SERVICE_ROLE_SECRET="$(read_env_key backend/.env SUPABASE_SERVICE_ROLE_SECRET || true)"
SUPABASE_KEY="$(read_env_key backend/.env SUPABASE_KEY || true)"
SUPABASE_JWT_SECRET="$(read_env_key backend/.env SUPABASE_JWT_SECRET || true)"
ANON_KEY="$(read_env_key frontend/.env.local NEXT_PUBLIC_SUPABASE_ANON_KEY || true)"

[ -n "${SUPABASE_URL:-}" ] || fail "backend/.env missing SUPABASE_URL"
[ -n "${ANON_KEY:-}" ] || fail "frontend/.env.local missing NEXT_PUBLIC_SUPABASE_ANON_KEY"

OUT_FILE="$ROOT/.smoke.env"
if [ -f "$OUT_FILE" ]; then
  pass ".smoke.env already exists (not changing)"
  exit 0
fi

umask 077

if [ -n "${SMOKE_EMAIL:-}" ] && [ -n "${SMOKE_PASSWORD:-}" ]; then
  LOGIN_CODE="$(curl -sS -o /tmp/smoke_setup_login.json -w "%{http_code}" -X POST "$SUPABASE_URL/auth/v1/token?grant_type=password" \
    -H "apikey: $ANON_KEY" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"$SMOKE_EMAIL\",\"password\":\"$SMOKE_PASSWORD\"}")" || true
  if [ "$LOGIN_CODE" = "200" ]; then
    umask 077
    cat >"$OUT_FILE" <<EOF
# Auto-generated by scripts/smoke_setup.sh (gitignored)
SMOKE_EMAIL="$SMOKE_EMAIL"
SMOKE_PASSWORD="$SMOKE_PASSWORD"
EOF
    pass "existing SMOKE_EMAIL/SMOKE_PASSWORD validated and stored in .smoke.env"
    pass "next: ./scripts/smoke.sh"
    exit 0
  else
    echo "WARN: provided SMOKE_EMAIL/SMOKE_PASSWORD invalid (status=$LOGIN_CODE); will attempt admin creation."
  fi
fi

# Generate deterministic-ish credentials without printing the password.
SMOKE_EMAIL="smoke.$(date +%Y%m%d%H%M%S)@example.com"
SMOKE_PASSWORD="$(python3 -c 'import secrets; print(secrets.token_urlsafe(18))')"

# Build a fallback service-role JWT if provided service key is invalid.
build_service_jwt() {
  python3 - "$SUPABASE_URL" "$SUPABASE_KEY" "$SUPABASE_JWT_SECRET" <<'PY'
from __future__ import annotations
import base64, hashlib, hmac, json, os, sys, time
from urllib.parse import urlparse

supabase_url, anon_key, jwt_secret = sys.argv[1], sys.argv[2], sys.argv[3]
if not supabase_url or not jwt_secret:
    raise SystemExit(1)
host = (urlparse(supabase_url).hostname or "")
ref = host.split(".")[0] if host else ""
if not ref:
    raise SystemExit(1)

def b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).decode().rstrip("=")

now = int(time.time())
header = {"alg": "HS256", "typ": "JWT"}

payload = {"iss": "supabase", "ref": ref, "role": "service_role", "iat": now, "exp": now + 60 * 60 * 24 * 365 * 5}
msg = f"{b64url(json.dumps(header, separators=(',', ':')).encode())}.{b64url(json.dumps(payload, separators=(',', ':')).encode())}"

secrets: list[bytes] = []
raw = jwt_secret.encode()
secrets.append(raw)
try:
    dec = base64.b64decode(jwt_secret)
    if dec:
        secrets.append(dec)
except Exception:
    pass

for s in secrets:
    sig = hmac.new(s, msg.encode(), hashlib.sha256).digest()
    print(f"{msg}.{b64url(sig)}")
PY
}

AUTH_KEYS=()
# New Supabase "secret key" format (sb_secret_...) works for admin APIs.
if [ -n "${SUPABASE_SECRET_KEY:-}" ]; then AUTH_KEYS+=("$SUPABASE_SECRET_KEY"); fi
if [ -n "${SUPABASE_SECRET:-}" ]; then AUTH_KEYS+=("$SUPABASE_SECRET"); fi
if [ -n "${SUPABASE_SERVICE_ROLE_SECRET:-}" ]; then AUTH_KEYS+=("$SUPABASE_SERVICE_ROLE_SECRET"); fi

if [ -n "${SERVICE_ROLE_KEY:-}" ]; then AUTH_KEYS+=("$SERVICE_ROLE_KEY"); fi
if [ -n "${SUPABASE_JWT_SECRET:-}" ]; then
  while IFS= read -r line; do
    [ -n "$line" ] && AUTH_KEYS+=("$line")
  done < <(build_service_jwt || true)
fi

[ "${#AUTH_KEYS[@]}" -gt 0 ] || fail "backend/.env missing usable admin key material. Provide SUPABASE_SECRET_KEY (preferred) or SUPABASE_SERVICE_ROLE_KEY, or set SMOKE_EMAIL/SMOKE_PASSWORD."

CREATE_RESP=""
CREATE_CODE=""
for KEY in "${AUTH_KEYS[@]}"; do
  CREATE_CODE="$(curl -sS -o /tmp/smoke_setup_create.json -w "%{http_code}" -X POST "$SUPABASE_URL/auth/v1/admin/users" \
    -H "apikey: $KEY" \
    -H "Authorization: Bearer $KEY" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"$SMOKE_EMAIL\",\"password\":\"$SMOKE_PASSWORD\",\"email_confirm\":true}")" || fail "admin user create request failed"
  CREATE_RESP="$(cat /tmp/smoke_setup_create.json)"
  if [ "$CREATE_CODE" = "200" ]; then
    break
  fi
done

if [ "$CREATE_CODE" != "200" ]; then
  SAFE_MSG="$(python3 - <<'PY'
import json
try:
    obj = json.load(open("/tmp/smoke_setup_create.json"))
except Exception:
    print("unknown")
    raise SystemExit
msg = ""
if isinstance(obj, dict):
    msg = obj.get("msg") or obj.get("message") or obj.get("error") or obj.get("error_description") or "unknown"
print(msg)
PY
)"
  # Fallback path: try self-signup with anon key if admin API key is unavailable.
  SIGNUP_CODE="$(curl -sS -o /tmp/smoke_setup_signup.json -w "%{http_code}" -X POST "$SUPABASE_URL/auth/v1/signup" \
    -H "apikey: $ANON_KEY" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"$SMOKE_EMAIL\",\"password\":\"$SMOKE_PASSWORD\"}")" || true
  if [ "$SIGNUP_CODE" = "200" ]; then
    LOGIN_CODE="$(curl -sS -o /tmp/smoke_setup_login.json -w "%{http_code}" -X POST "$SUPABASE_URL/auth/v1/token?grant_type=password" \
      -H "apikey: $ANON_KEY" \
      -H "Content-Type: application/json" \
      -d "{\"email\":\"$SMOKE_EMAIL\",\"password\":\"$SMOKE_PASSWORD\"}")" || true
    if [ "$LOGIN_CODE" = "200" ]; then
      cat >"$OUT_FILE" <<EOF
# Auto-generated by scripts/smoke_setup.sh (gitignored)
SMOKE_EMAIL="$SMOKE_EMAIL"
SMOKE_PASSWORD="$SMOKE_PASSWORD"
EOF
      pass "admin create failed, but anon signup+login succeeded"
      pass "created .smoke.env from generated credentials"
      pass "next: ./scripts/smoke.sh"
      exit 0
    fi
  fi
  if [ -n "${SMOKE_EMAIL:-}" ] && [ -n "${SMOKE_PASSWORD:-}" ]; then
    LOGIN_CODE="$(curl -sS -o /tmp/smoke_setup_login.json -w "%{http_code}" -X POST "$SUPABASE_URL/auth/v1/token?grant_type=password" \
      -H "apikey: $ANON_KEY" \
      -H "Content-Type: application/json" \
      -d "{\"email\":\"$SMOKE_EMAIL\",\"password\":\"$SMOKE_PASSWORD\"}")" || true
    if [ "$LOGIN_CODE" = "200" ]; then
      cat >"$OUT_FILE" <<EOF
# Auto-generated by scripts/smoke_setup.sh (gitignored)
SMOKE_EMAIL="$SMOKE_EMAIL"
SMOKE_PASSWORD="$SMOKE_PASSWORD"
EOF
      pass "admin create failed, but existing SMOKE_EMAIL/SMOKE_PASSWORD are valid"
      pass "created .smoke.env from provided credentials"
      pass "next: ./scripts/smoke.sh"
      exit 0
    fi
  fi
  fail "smoke user setup failed (admin status=$CREATE_CODE message=$SAFE_MSG; signup status=${SIGNUP_CODE:-unknown}). Set backend SUPABASE_SECRET_KEY (preferred) or provide SMOKE_EMAIL/SMOKE_PASSWORD for an existing user."
fi

cat >"$OUT_FILE" <<EOF
# Auto-generated by scripts/smoke_setup.sh (gitignored)
SMOKE_EMAIL="$SMOKE_EMAIL"
SMOKE_PASSWORD="$SMOKE_PASSWORD"
EOF

pass "created .smoke.env (credentials stored locally; not printed)"
pass "next: ./scripts/smoke.sh"
